### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by sahil-banswani**
Updated the readme file and added the perfect link to the folder structure

### CODE REVIEW

**Comment by sahil-banswani** [comment]
updated the Navigation for the ease of User

**Comment by prasanna-muppidwar** [comment]
Hi Sahil! The Folder Structure is indeed well formed but the Main Branch is Few Commits Forward than your commit and it will disturb the entire documentation of the Repo! This cant be merged due to certain issues! Thank you :)

**Comment by sahil-banswani** [comment]
What's the issue can you elaborate.

**Comment by prasanna-muppidwar** [comment]
Basically the Readme and Folder Structure is Updated but your Pr does not meet the Current Updated Folder Structure, Firstly you have to Sync your fork and then clone it to add your changes before merging the request to full fill our requirement for a merge.

**Pull request closed without merging**
